services:
  dev:
    container_name: gato-container
    image: gato
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    tty: true
    stdin_open: true
