services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true

    
# sudo setfacl --modify user:<USER>:rw /var/run/docker.sock
