#pragma once
// GENERATED by gato.builder (_write_gato_abi) for go2 — DO NOT EDIT.
// Caller-scratch arena element offsets for the grid_plant step surfaces,
// parsed from the generated grid.cuh kernel arena recipes. Emitted for
// FLOATING-BASE robots only; its presence is the preprocessor-level
// floating fact (__has_include in dynamics/grid_plant_step.cuh).
// The int topology region and the (constexpr-sized) linalg helper bytes
// are carved AFTER the T region by the consumer.
#define GATO_GRID_STEP_ABI 1

// fixed-target EE-pose inner names (suffixed with the EE frame name)
#define GATO_GRID_EE_POSE_INNER end_effector_pose_inner_imu_joint
#define GATO_GRID_EE_POSE_GRAD_INNER end_effector_pose_gradient_inner_imu_joint

namespace gato_abi {

// integrator_with_gradient_kernel (TIER_SHARED / SCRATCH_IN_SMEM=true)
inline constexpr int SG_Q_QD_U = 0;  // [57]
inline constexpr int SG_DAB = 57;  // [1944]
inline constexpr int SG_DF_DU = 2001;  // [648]
inline constexpr int SG_DC_DU = 2649;  // [648]
inline constexpr int SG_VAF = 3297;  // [324]
inline constexpr int SG_MINV = 3621;  // [324]
inline constexpr int SG_QDD = 3945;  // [18]
inline constexpr int SG_Q_ORIG = 3963;  // [19]
inline constexpr int SG_QD_ORIG = 3982;  // [18]
inline constexpr int SG_STAGE_GRAD_QDD = 4000;  // [72]
inline constexpr int SG_D_QDD_STAGE = 4072;  // [3888]
inline constexpr int SG_DINT_Q_6X6 = 7960;  // [36]
inline constexpr int SG_DINT_V_6X6 = 7996;  // [36]
inline constexpr int SG_X_KP1 = 8032;  // [37]
inline constexpr int SG_XIMATS = 8069;  // [936]
inline constexpr int SG_TEMP = 9005;  // [9612]
inline constexpr int SG_T_COUNT = 18617;
inline constexpr int SG_TOPOLOGY_INT_COUNT = 115;

// integrator_kernel (TIER_SHARED / SCRATCH_IN_SMEM=true)
inline constexpr int ST_Q_QD_U = 0;  // [57]
inline constexpr int ST_QDD = 57;  // [18]
inline constexpr int ST_STAGE_QDD = 75;  // [54]
inline constexpr int ST_STAGE_POINT = 129;  // [111]
inline constexpr int ST_X_KP1 = 240;  // [37]
inline constexpr int ST_XIMATS = 277;  // [936]
inline constexpr int ST_TEMP = 1213;  // [3398]
inline constexpr int ST_T_COUNT = 4611;
inline constexpr int ST_TOPOLOGY_INT_COUNT = 115;

}  // namespace gato_abi
