
# fixed:
#   precision: float  # Options: float(32), double(64)
#   batch_size: 64
#   num_alphas: 16

# variable:
#   knot_points: 64

f_ext_knots: 64 # number of knots to apply simulated external wrench

integrator_type: 2 # 0: euler, 1: semi-implicit euler, 2: trapezoidal

# Cost Weights
costs:
  velocity: 1.0e-2
  control: 1.0e-8
  terminal: 100.0
  joint_limit_barrier: 0.05

# SQP
sqp:
  max_iterations: 4
  pcg:
    max_iterations: 200
    tolerance: 1.0e-5  # relative tolerance
  rho:
    init: 1.0e-5
    factor: 1.2
    max: 10.0
    min: 1.0e-8
  num_alphas: 16 # line search

# CUDA number of threads
threads:
  kkt: 256
  schur: 256
  pcg: 1024
  dz: 256
  merit: 256
  line_search: 256
  sim_forward: 256

# Robot Dynamics Model
robot: indy7 
