# GATO Configuration File

# General Settings
precision: float  # Options: float(32), double(64)
knot_points: 64
f_ext_knots: 64


# Cost Weights
costs:
  control: 1.0e-8
  velocity: 1.0e-2
  terminal: 100.0
  barrier: 0.05

# SQP
sqp:
  max_iterations: 4
  pcg:
    max_iterations: 200
    tolerance: 1.0e-5  # relative tolerance

# Line Search
num_alphas: 16


# Augmented Lagrangian Parameters
augmented_lagrangian:
  rho_init: 1.0e-5
  rho_factor: 1.2
  rho_max: 10.0
  rho_min: 1.0e-8

# CUDA Thread Configuration
threads:
  kkt: 128
  schur: 128
  pcg: 1024
  dz: 128
  merit: 128
  line_search: 128
  sim_forward: 128

# Robot Configuration
robot: indy7  # Options: indy7, iiwa14
