solver:
  # plant_path: "dynamics/indy7/indy7_plant.cuh" # grid dynamics model
  # integrator_type: 2 # 0: euler, 1: semi-implicit euler, 2: trapezoidal

  #ctrl_freq: 500 # TODO:

  batch_size: 32
  N_h: 32
  dt: 0.01

  f_ext_horizon: 64 # number of knots to apply simulated external wrench

  sqp_tol: 1.0e-5 # TODO: infinity norm of KKT residual
  sqp_max_iter: 5

  pcg_tol: 5.0e-5 # relative tolerance
  pcg_max_iter: 150

  num_alphas: 16 # step sizes for line search

cost:
  ee_pos_weights: [1.0, 1.0, 1.0]
  ee_pos_reg: 5.0
  ee_pos_reg_terminal: 50.0

  joint_limit_barrier: 0.05
  #TODO: control limit barrier

  # state
  # - higher penalties for joint positions, lower penalties for velocities
  # - penalize first 3 (heavier) joints more
  # - can increase velocity weights for smoother/stable trajectories
  x_reg_weights: [10., 10., 10., 5., 5., 5, 1., 1., 1., 1., 1., 1.]
  x_reg: 0.01 # initial value
  x_reg_terminal: 0.01

  # control
  # - penalize torques for smaller actuators?
  # - scale inversely with torque limits?
  u_reg_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  u_reg: 0.00001 # initial value
  u_reg_terminal: 0.00001

  reg_factor: 10.0
  reg_max: 1.0e9
  reg_min: 1.0e-9

threads: # kernel thread block sizes
  kkt: 128
  schur: 128
  pcg: 1024
  dz: 128
  merit: 128
  line_search: 128
  sim_forward: 128
