#!/usr/bin/env bash
# Build the faithful batched-CPU baseline (pysqpcpu / BatchThneed, the paper's Fig-3 CPU
# competitor) WITHOUT the heavy ROS + source-pinocchio install the upstream Dockerfile uses.
#
# Key shortcut: the GRiD venv already ships pinocchio + hpp-fcl(coal) + Eigen C++ *and their
# CMake configs* via `cmeel` (pip install pin), so we only build the two genuinely-missing
# pieces — osqp + osqp-eigen — into a LOCAL prefix (no sudo, no system pollution), then build
# the pysqpcpu pybind module against the venv's pinocchio.
#
# Usage:
#   baselines/build_cpu_baseline.sh [VENV_DIR]      # default: ../GRiD/.venv
# After it finishes, run anything that imports pysqpcpu with:
#   source baselines/sqpcpu_env.sh                  # sets LD_LIBRARY_PATH + PYTHONPATH
#
# System prerequisites (Ubuntu; already present on this box): build-essential cmake git
#   libeigen3-dev liburdfdom-dev.  (pinocchio/hpp-fcl/Eigen C++ come from the venv's cmeel,
#   so NO ROS and NO source pinocchio build are needed.)
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SQPCPU="$REPO/baselines/sqpcpu"
DEPS="$SQPCPU/deps"
PREFIX="$DEPS/install"
VENV="${1:-$(dirname "$REPO")/GRiD/.venv}"
PY="$VENV/bin/python"

[ -x "$PY" ] || { echo "ERROR: venv python not found at $PY (pass VENV_DIR as arg 1)"; exit 1; }
"$PY" -c "import pinocchio" 2>/dev/null || { echo "ERROR: $PY lacks pinocchio (pip install pin)"; exit 1; }
CMEEL="$("$PY" -c "import pinocchio,os; print(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(pinocchio.__file__)))))")"
echo "REPO=$REPO"; echo "VENV=$VENV"; echo "CMEEL=$CMEEL"; echo "PREFIX=$PREFIX"
mkdir -p "$DEPS"

# --- osqp v0.6.3 (pinned: osqp-eigen 0.8.x targets the 0.6.x C API; v1.0 changed it) ---
if [ ! -f "$PREFIX/lib/cmake/osqp/osqp-config.cmake" ]; then
  echo "=== building osqp v0.6.3 ==="
  rm -rf "$DEPS/osqp_src"
  git clone --recursive --branch v0.6.3 --depth 1 https://github.com/osqp/osqp "$DEPS/osqp_src"
  cmake -S "$DEPS/osqp_src" -B "$DEPS/osqp_src/build" -G "Unix Makefiles" \
        -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  cmake --build "$DEPS/osqp_src/build" --target install -j"$(nproc)"
else echo "=== osqp already installed ==="; fi

# --- osqp-eigen v0.8.1 (matches osqp 0.6.3) ---
if [ ! -f "$PREFIX/lib/cmake/OsqpEigen/OsqpEigenConfig.cmake" ]; then
  echo "=== building osqp-eigen v0.8.1 ==="
  rm -rf "$DEPS/osqpeigen_src"
  git clone --branch v0.8.1 --depth 1 https://github.com/robotology/osqp-eigen.git "$DEPS/osqpeigen_src"
  cmake -S "$DEPS/osqpeigen_src" -B "$DEPS/osqpeigen_src/build" \
        -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_PREFIX_PATH="$PREFIX" \
        -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  cmake --build "$DEPS/osqpeigen_src/build" --target install -j"$(nproc)"
else echo "=== osqp-eigen already installed ==="; fi

# --- pysqpcpu (BatchThneed) against cmeel pinocchio + local osqp ---
echo "=== building pysqpcpu (BatchThneed) ==="
cmake -S "$SQPCPU" -B "$SQPCPU/build" \
      -DCMAKE_PREFIX_PATH="$PREFIX;$CMEEL" \
      -DPython3_EXECUTABLE="$PY" \
      -Dpybind11_DIR="$("$PY" -m pybind11 --cmakedir)" \
      -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF
cmake --build "$SQPCPU/build" --target pysqpcpu -j"$(nproc)"

# --- write the env helper to source before importing pysqpcpu ---
cat > "$REPO/baselines/sqpcpu_env.sh" <<EOF
# Source this before importing pysqpcpu (BatchThneed). Auto-generated by build_cpu_baseline.sh.
export LD_LIBRARY_PATH="$SQPCPU/build:$PREFIX/lib:$CMEEL/lib:\${LD_LIBRARY_PATH:-}"
export PYTHONPATH="$SQPCPU/build:\${PYTHONPATH:-}"
EOF

echo "=== verifying import ==="
# shellcheck disable=SC1090
source "$REPO/baselines/sqpcpu_env.sh"
"$PY" -c "import pysqpcpu; print('pysqpcpu OK:', [x for x in dir(pysqpcpu) if 'Thneed' in x])"
echo "DONE. Run baselines with:  source baselines/sqpcpu_env.sh"
